language: cpp

env:
  global:
   # Encrypted COVERITY_SCAN_TOKEN
   - secure: "hka+won1cBe8PDoVFK3etxugDl/GuJwUsGfag/Bw6yWV+Q8DZpvzBKDzMJ+kuLPzyMUb6HhJM6ATMuOx3n2mBbeYx7uFpx4fvWdp34+2Yi5/dVY95icQd3kmkwi9SgECUGCIrgWXAR9e3w7GWQEMvkvHFvcinQIzsT20a29bKceKNGtot8EThfgLFMSAX9ofDt1D4dtvEKJdH1Zr8e3Ce+gb41u78Ce85POZUN3nwaOc9K8tysnxl34MZcLUkWG/gSj4mjbkc4+dXYOgcxFkn8IU4qwYMaRW7GpwhV6e3B1rZfrp9AN5a7iLW+i8Kv2ZibH4+JUfpa5N6mrT2DPFerNiQ6Dh/RJKdE4FiYcsgHrw0W2DN1CYYjKba9pVRwqOWe68+2wNRaSCXYZLqB2vG5OjAh53iG/t9M8HaMPqE+yKKEiFtQbKOuy8X+HBLxQNNIkgQDRLlN6YNkZCMpeExMzrhbAPvqjagfwNFpflmXY2rnG9Q/9FY8BLu9HnH1jyWMCdA2ORUXmaNswEjeN+a91S80bVDIkqegI27ik+fTybqVkiB35/WU+hIuv2C88MsP1MhHc075d4t7Wto0nbd6T+/z5N6rDGpRfy39wCL0ESlYNRE0M0UPLO/ykH6uUcEADxmv1F72P8RPewou/HMjM2Q00tfVQa2LyZnbTo2uo="

script:
  - cd SAP-Report-Source-Decompressor
  - make
  - make test

notifications:
  email:
    recipients:
      - mail@daniel-berlin.de
    on_success: change
    on_failure: always

addons:
  coverity_scan:
    project:
      name: "daberlin/sap-reposrc-decompressor"
      description: "SAP Report Source Decompressor"
    notification_email: mail@daniel-berlin.de
    build_command_prepend: "cd SAP-Report-Source-Decompressor"
    build_command: "make"
    branch_pattern: master
