language: cpp

script:
  - cd SAP-Report-Source-Decompressor
  - bash build.sh

notifications:
  email:
    recipients:
      - mail@daniel-berlin.de
    on_success: change
    on_failure: always
