os: Visual Studio 2015
version: "{branch}-{build}"

platform:
  - x86
  - x64

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %platform%

build_script:
  - cd SAP-Report-Source-Decompressor
  - MSBuild.exe /l:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /v:d

test_script:
  - MSBuild.exe /t:Test /l:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /v:d

notifications:
  - provider: Email
    to: mail@daniel-berlin.de
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
